
GET http://localhost:3000


####### USER ######

###
GET http://localhost:3000/api/v1/user/test/all HTTP/1.1

POST http://localhost:3000/api/v1/invoice/new HTTP/1.1
content-type: application/json

{
    "patientData": {
        "name": "78",
        "age": "dgd",
        "gender": "m2ale",
        "contact" : "12345678901",
        "doctorName": "Dr. Strange"
    }, 
    "invoiceData": {
        "referrerId": "605",
        "total": 1200,
        "discount": 200,
        "paid" : 44,
        "testList": ["CBC", "X-Ray", "ECG"]
    }
}


###
GET http://localhost:3000/api/v1/invoice HTTP/1.1
content-type: application/json

{
   "_id": "673e338edc8fb8f1995d12ec"
}


###
PUT http://localhost:3000/api/v1/invoice/update HTTP/1.1
content-type: application/json

{
   "update": "paid",
   "_id": "673dd92243bfcbbe6eda"
}

###
GET http://localhost:3000/api/v1/user/test/all HTTP/1.1



######## ADMIN ########

###
GET http://localhost:3000/api/v1/global/test/all HTTP/1.1




###
POST http://localhost:3000/api/v1/global/test/add HTTP/1.1
content-type: application/json

{
   "name": "Colonoscopy",
   "code": "colonoscopy",
   "description": "description for XRay",
   "type": 2,
   "format": "standard"

}