
GET http://localhost:3000


####### USER ######

# User testlist
###
GET http://localhost:3000/api/v1/user/test/all HTTP/1.1

# Create Invoice
POST http://localhost:3000/api/v1/invoice/new HTTP/1.1
content-type: application/json

{
    "patientData": {
        "name": "78",
        "age": "dgd",
        "gender": "m2ale",
        "contact" : "12345678901",
        "doctorName": "Dr. Strange"
    }, 
    "invoiceData": {
        "referrerId": "605",
        "total": 1200,
        "discount": 200,
        "paid" : 44,
        "testList": ["CBC", "X-Ray", "ECG"]
    }
}


# Find invoices by Date
###
GET http://localhost:3000/api/v1/invoice/date HTTP/1.1

# Find an invoice
###
GET http://localhost:3000/api/v1/invoice HTTP/1.1
content-type: application/json

{
   "_id": "673e338edc8fb8f1995d12ec"
}


# Update invoice
###
PUT http://localhost:3000/api/v1/invoice/update HTTP/1.1
content-type: application/json

{
   "update": "paid",
   "_id": "673dd92243bfcbbe6eda"
}


# User test list
###
GET http://localhost:3000/api/v1/user/test/all HTTP/1.1




######## System ########

# All Test List
###
GET http://localhost:3000/api/v1/system/test/all HTTP/1.1


# Add a new user
###
POST http://localhost:3000/api/v1/system/user/add HTTP/1.1
content-type: application/json

{
   "labName": "Phoenix Diagonostic Center",
   "contact": "01723xxxxxx",
   "email": "az15624@gmail.com",
   "testList": []

}

# Add a new test
###
POST http://localhost:3000/api/v1/system/test/add HTTP/1.1
content-type: application/json

{
   "name": "Test 7",
   "code": "sgs",
   "description": "description for colonoscopy",
   "type": 1,
   "format": "standard"

}


# Convert Date
###
POST http://localhost:3000/convert-date HTTP/1.1
content-type: application/json

{
   "dateString": "2024-12-06"

}

# Create a new lab

###
POST http://localhost:3000/api/v1/system/lab/add HTTP/1.1
content-type: application/json

{
    "labName": "City Diagnostic Center 2",
    "zone": "Mymensingh",
    "address": "123 Medical Street, Healthcare City",
    "email": "contact@citydiagnostic.com",
    "contact1": 1234567890,
    "contact2": 9876543210,
    "invoicePrice": 10,
    "labIncentive": 5
}
